### ISSUE TITLE
"cd" command does not work in mask

### ISSUE THREAD

**Issue by zen** [jakedeichert/mask#82] opened 2021-04-06 12:21 UTC
Hi there, great tool.

I have a very weird issue with mask. I defined really simple maskfile:

```
# Common Tasks
easy tedious task management

## go
> go to common folders

### go work 
> go to work folder

~~~sh
echo "changing dir..."
cd $HOME/projects/work
~~~

after launching `mask go work` I'm still in current folder. I tried changing interpreter (sh, bash, zsh), interpolation, removing variables at all with no avail. I guess that must be something trivial I'm missing.

Mac OS X 11.2.3
zsh 5.8 (x86_64-apple-darwin20.0)
mask 0.10.0

**Comment by zen** [comment] 2021-04-06 12:25
All right, now I understand after tracing the entire execution. So actually mask cannot be used for such pattern, it spawns new shell process, executes commands and closes, so you would and up in the calling shell process and original dir.

**Comment by jakedeichert** [comment] 2021-04-07 02:35
Hey, thanks for checking out mask!

You're right, that's not how mask works. Mask runs the task/script within a subprocess it spawns instead of operating within the current process/shell.

If you want to get a bit creative, you could make a mask cmd that echos some bash aliases/variables/helpers and you could possibly `source` those into your current shell process.

**Comment by jakedeichert** [comment] 2021-04-07 02:36
Going to close this as it's not a bug 👍

**Closed by jakedeichert** 2021-04-07 02:36 UTC
